/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Lauti
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpHome = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        itmenuLocadores = new javax.swing.JMenuItem();
        itmenuLocatarios = new javax.swing.JMenuItem();
        itmenuInmuebles = new javax.swing.JMenuItem();
        itmenuLegajos = new javax.swing.JMenuItem();
        itmenuLegajosViejos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inmobiliaria Mi MAIPU");

        dpHome.setBackground(new java.awt.Color(255, 255, 255));
        dpHome.setDesktopManager(null);

        javax.swing.GroupLayout dpHomeLayout = new javax.swing.GroupLayout(dpHome);
        dpHome.setLayout(dpHomeLayout);
        dpHomeLayout.setHorizontalGroup(
            dpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        dpHomeLayout.setVerticalGroup(
            dpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenu2.setText("Catálogo");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        itmenuLocadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        itmenuLocadores.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        itmenuLocadores.setText("Locadores");
        itmenuLocadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuLocadoresActionPerformed(evt);
            }
        });
        jMenu2.add(itmenuLocadores);

        itmenuLocatarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        itmenuLocatarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        itmenuLocatarios.setText("Locatarios");
        jMenu2.add(itmenuLocatarios);

        itmenuInmuebles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        itmenuInmuebles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        itmenuInmuebles.setText("Inmuebles");
        jMenu2.add(itmenuInmuebles);

        itmenuLegajos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itmenuLegajos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        itmenuLegajos.setText("Legajos");
        jMenu2.add(itmenuLegajos);

        itmenuLegajosViejos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        itmenuLegajosViejos.setText("Legajos Viejos");
        itmenuLegajosViejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmenuLegajosViejosActionPerformed(evt);
            }
        });
        jMenu2.add(itmenuLegajosViejos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpHome)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmenuLocadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuLocadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmenuLocadoresActionPerformed

    private void itmenuLegajosViejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmenuLegajosViejosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmenuLegajosViejosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane dpHome;
    public javax.swing.JMenuItem itmenuInmuebles;
    public javax.swing.JMenuItem itmenuLegajos;
    public javax.swing.JMenuItem itmenuLegajosViejos;
    public javax.swing.JMenuItem itmenuLocadores;
    public javax.swing.JMenuItem itmenuLocatarios;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
