/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Lauti
 */
public class JfDetallesLegajo extends javax.swing.JFrame {

    /**
     * Creates new form JfDetallesRegistro
     */
    public JfDetallesLegajo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label0 = new javax.swing.JLabel();
        legajo = new javax.swing.JLabel();
        legajo2 = new javax.swing.JLabel();
        tipoInmueble = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        legajo40 = new javax.swing.JLabel();
        pisoDepto = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        barrio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        legajo3 = new javax.swing.JLabel();
        legajo4 = new javax.swing.JLabel();
        legajo5 = new javax.swing.JLabel();
        locadorNombre = new javax.swing.JLabel();
        locadorTelefono = new javax.swing.JLabel();
        locadorMail = new javax.swing.JLabel();
        legajo6 = new javax.swing.JLabel();
        locadorDomicilio = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        legajo7 = new javax.swing.JLabel();
        legajo8 = new javax.swing.JLabel();
        legajo13 = new javax.swing.JLabel();
        locatarioTelefono = new javax.swing.JLabel();
        locatarioNombre = new javax.swing.JLabel();
        locatarioMail = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        legajo9 = new javax.swing.JLabel();
        legajo10 = new javax.swing.JLabel();
        legajo11 = new javax.swing.JLabel();
        legajo12 = new javax.swing.JLabel();
        legajo14 = new javax.swing.JLabel();
        garante1Nombre = new javax.swing.JLabel();
        garante1Domicilio = new javax.swing.JLabel();
        garante1Telefono = new javax.swing.JLabel();
        garante1Mail = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        legajo15 = new javax.swing.JLabel();
        legajo16 = new javax.swing.JLabel();
        legajo17 = new javax.swing.JLabel();
        legajo18 = new javax.swing.JLabel();
        legajo19 = new javax.swing.JLabel();
        garante2Nombre = new javax.swing.JLabel();
        garante2Domicilio = new javax.swing.JLabel();
        garante2Telefono = new javax.swing.JLabel();
        garante2Mail = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        legajo20 = new javax.swing.JLabel();
        legajo21 = new javax.swing.JLabel();
        legajo22 = new javax.swing.JLabel();
        legajo23 = new javax.swing.JLabel();
        legajo24 = new javax.swing.JLabel();
        garante3Nombre = new javax.swing.JLabel();
        garante3Domicilio = new javax.swing.JLabel();
        garante3Telefono = new javax.swing.JLabel();
        garante3Mail = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        legajo25 = new javax.swing.JLabel();
        legajo26 = new javax.swing.JLabel();
        legajo27 = new javax.swing.JLabel();
        legajo28 = new javax.swing.JLabel();
        legajo29 = new javax.swing.JLabel();
        garante4Nombre = new javax.swing.JLabel();
        garante4Domicilio = new javax.swing.JLabel();
        garante4Telefono = new javax.swing.JLabel();
        garante4Mail = new javax.swing.JLabel();
        legajo37 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOtrosGarantes = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        legajo39 = new javax.swing.JLabel();
        legajo30 = new javax.swing.JLabel();
        legajo31 = new javax.swing.JLabel();
        legajo32 = new javax.swing.JLabel();
        legajo33 = new javax.swing.JLabel();
        legajo34 = new javax.swing.JLabel();
        legajo35 = new javax.swing.JLabel();
        legajo36 = new javax.swing.JLabel();
        legajo38 = new javax.swing.JLabel();
        montoAlquiler = new javax.swing.JLabel();
        fechaSubscripcion = new javax.swing.JLabel();
        fechaInicio = new javax.swing.JLabel();
        fechaFinalizacion = new javax.swing.JLabel();
        legajo63 = new javax.swing.JLabel();
        legajo58 = new javax.swing.JLabel();
        legajo62 = new javax.swing.JLabel();
        legajo64 = new javax.swing.JLabel();
        legajo65 = new javax.swing.JLabel();
        legajo66 = new javax.swing.JLabel();
        legajo67 = new javax.swing.JLabel();
        legajo68 = new javax.swing.JLabel();
        titularExpensas = new javax.swing.JLabel();
        titularGas = new javax.swing.JLabel();
        titularLuz = new javax.swing.JLabel();
        titularAgua = new javax.swing.JLabel();
        titularDgr = new javax.swing.JLabel();
        titularImpuestoMunicipal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        impuestoMunicipal = new javax.swing.JLabel();
        dgr = new javax.swing.JLabel();
        agua = new javax.swing.JLabel();
        luz = new javax.swing.JLabel();
        gas = new javax.swing.JLabel();
        expensas = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        btnDetallesLocador = new javax.swing.JButton();
        btnDetallesInmueble = new javax.swing.JButton();
        btnDetallesLocatario = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnGenerarRecibo = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();

        setResizable(false);

        label0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label0.setText("Tipo de inmueble:");

        legajo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        legajo.setText("NºL");

        legajo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo2.setText("Dirección:");

        tipoInmueble.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoInmueble.setText("Tipo de inmueble?");

        direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direccion.setText("Dirección?");

        label8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label8.setText("Estado:");

        estado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estado.setText("Estado?");

        legajo40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo40.setText("Piso - Depto:");

        pisoDepto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pisoDepto.setText("PisoDepto?");

        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setText("Barrio:");

        barrio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barrio.setText("barrio?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(legajo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label0)
                    .addComponent(legajo2)
                    .addComponent(legajo40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(label8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pisoDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(476, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(legajo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label0)
                            .addComponent(tipoInmueble)
                            .addComponent(label8)
                            .addComponent(estado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(legajo2)
                            .addComponent(direccion)
                            .addComponent(label1)
                            .addComponent(barrio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(legajo40)
                            .addComponent(pisoDepto)))))
        );

        legajo3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo3.setText("Locador:");

        legajo4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo4.setText("Nº Teléfono:");

        legajo5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo5.setText("Mail:");

        locadorNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locadorNombre.setText("Locador?");

        locadorTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locadorTelefono.setText("Nº Teléfono?");

        locadorMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locadorMail.setText("Mail?");

        legajo6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo6.setText("Domicilio:");

        locadorDomicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locadorDomicilio.setText("Domicilio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legajo4)
                    .addComponent(legajo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locadorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locadorNombre))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legajo6)
                    .addComponent(legajo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locadorMail, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locadorDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(locadorNombre)
                        .addComponent(legajo6)
                        .addComponent(locadorDomicilio))
                    .addComponent(legajo3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo4)
                    .addComponent(legajo5)
                    .addComponent(locadorTelefono)
                    .addComponent(locadorMail))
                .addGap(5, 5, 5))
        );

        legajo7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo7.setText("Nº Teléfono:");

        legajo8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo8.setText("Mail:");

        legajo13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo13.setText("Locatario:");

        locatarioTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locatarioTelefono.setText("Nº Teléfono?");

        locatarioNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locatarioNombre.setText("Locatario?");

        locatarioMail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locatarioMail.setText("Mail?");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legajo7)
                    .addComponent(legajo13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(locatarioTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(locatarioNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(legajo8)
                .addGap(41, 41, 41)
                .addComponent(locatarioMail, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo13)
                    .addComponent(locatarioNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo7)
                    .addComponent(legajo8)
                    .addComponent(locatarioTelefono)
                    .addComponent(locatarioMail))
                .addGap(6, 6, 6))
        );

        legajo9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo9.setText("Garante 1");

        legajo10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo10.setText("Nombre y apellido:");

        legajo11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo11.setText("Domicilio:");

        legajo12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo12.setText("Teléfono:");

        legajo14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo14.setText("Mail:");

        garante1Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante1Nombre.setText("Nombre y apellido?");

        garante1Domicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante1Domicilio.setText("Domicilio?");

        garante1Telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante1Telefono.setText("Teléfono?");

        garante1Mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante1Mail.setText("Mail?");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legajo9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(legajo10)
                            .addComponent(legajo11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(garante1Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(garante1Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(legajo14)
                                .addGap(43, 43, 43)
                                .addComponent(garante1Mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(legajo12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(garante1Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(legajo9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo10)
                    .addComponent(legajo12)
                    .addComponent(garante1Nombre)
                    .addComponent(garante1Telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo11)
                    .addComponent(legajo14)
                    .addComponent(garante1Domicilio)
                    .addComponent(garante1Mail))
                .addContainerGap())
        );

        legajo15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo15.setText("Garante 2");

        legajo16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo16.setText("Nombre y apellido:");

        legajo17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo17.setText("Domicilio:");

        legajo18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo18.setText("Teléfono:");

        legajo19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo19.setText("Mail:");

        garante2Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante2Nombre.setText("Nombre y apellido?");

        garante2Domicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante2Domicilio.setText("Domicilio?");

        garante2Telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante2Telefono.setText("Teléfono?");

        garante2Mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante2Mail.setText("Mail?");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legajo15)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(legajo16)
                            .addComponent(legajo17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(garante2Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(garante2Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(legajo19)
                                .addGap(43, 43, 43)
                                .addComponent(garante2Mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(legajo18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(garante2Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(legajo15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo16)
                    .addComponent(legajo18)
                    .addComponent(garante2Nombre)
                    .addComponent(garante2Telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo17)
                    .addComponent(legajo19)
                    .addComponent(garante2Domicilio)
                    .addComponent(garante2Mail))
                .addContainerGap())
        );

        legajo20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo20.setText("Garante 3");

        legajo21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo21.setText("Nombre y apellido:");

        legajo22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo22.setText("Domicilio:");

        legajo23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo23.setText("Teléfono:");

        legajo24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo24.setText("Mail:");

        garante3Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante3Nombre.setText("Nombre y apellido?");

        garante3Domicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante3Domicilio.setText("Domicilio?");

        garante3Telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante3Telefono.setText("Teléfono?");

        garante3Mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante3Mail.setText("Mail?");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legajo20)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(legajo21)
                            .addComponent(legajo22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(garante3Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(garante3Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(legajo24)
                                .addGap(43, 43, 43)
                                .addComponent(garante3Mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(legajo23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(garante3Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(legajo20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo21)
                    .addComponent(legajo23)
                    .addComponent(garante3Nombre)
                    .addComponent(garante3Telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo22)
                    .addComponent(legajo24)
                    .addComponent(garante3Domicilio)
                    .addComponent(garante3Mail))
                .addContainerGap())
        );

        legajo25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo25.setText("Garante 4");

        legajo26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo26.setText("Nombre y apellido:");

        legajo27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo27.setText("Domicilio:");

        legajo28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo28.setText("Teléfono:");

        legajo29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo29.setText("Mail:");

        garante4Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante4Nombre.setText("Nombre y apellido?");

        garante4Domicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante4Domicilio.setText("Domicilio?");

        garante4Telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante4Telefono.setText("Teléfono?");

        garante4Mail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        garante4Mail.setText("Mail?");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legajo25)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(legajo26)
                            .addComponent(legajo27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(garante4Domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(garante4Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(legajo29)
                                .addGap(43, 43, 43)
                                .addComponent(garante4Mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(legajo28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(garante4Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(legajo25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo26)
                    .addComponent(legajo28)
                    .addComponent(garante4Nombre)
                    .addComponent(garante4Telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajo27)
                    .addComponent(legajo29)
                    .addComponent(garante4Domicilio)
                    .addComponent(garante4Mail))
                .addContainerGap())
        );

        legajo37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        legajo37.setText("Otros garantes:");

        txtOtrosGarantes.setColumns(20);
        txtOtrosGarantes.setRows(5);
        txtOtrosGarantes.setText("Otros garantes?");
        jScrollPane2.setViewportView(txtOtrosGarantes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(legajo37)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(legajo37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        legajo39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo39.setText("Titular:");

        legajo30.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        legajo30.setText("Monto Alquiler:");

        legajo31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo31.setText("Rentas (DGR):");

        legajo32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo32.setText("Impuesto Municipal:");

        legajo33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo33.setText("Observaciones:");

        legajo34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo34.setText("Fecha de subscripción:");

        legajo35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo35.setText("Fecha de inicio:");

        legajo36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo36.setText("Fecha de finalización:");

        legajo38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo38.setText("Agua:");

        montoAlquiler.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        montoAlquiler.setText("Monto?");

        fechaSubscripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaSubscripcion.setText("Fecha de subscripción?");

        fechaInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaInicio.setText("Fecha de inicio?");

        fechaFinalizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaFinalizacion.setText("Fecha de finalización?");

        legajo63.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo63.setText("Titular:");

        legajo58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo58.setText("Luz (EPEC):");

        legajo62.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo62.setText("Gas (ECOGAS):");

        legajo64.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo64.setText("Expensas:");

        legajo65.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo65.setText("Titular:");

        legajo66.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo66.setText("Titular:");

        legajo67.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo67.setText("Titular:");

        legajo68.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        legajo68.setText("Titular:");

        titularExpensas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titularExpensas.setText("TitularExpensas?");

        titularGas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titularGas.setText("TitularGas?");

        titularLuz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titularLuz.setText("TitularLuz?");

        titularAgua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titularAgua.setText("TitularAgua?");

        titularDgr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titularDgr.setText("TitularRentas?");

        titularImpuestoMunicipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titularImpuestoMunicipal.setText("TitularImpuesto?");

        observaciones.setColumns(20);
        observaciones.setRows(5);
        observaciones.setText("Observaciones?\n");
        jScrollPane1.setViewportView(observaciones);

        impuestoMunicipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        impuestoMunicipal.setText("Impuesto Municipal?");

        dgr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dgr.setText("Rentas(DGR)?");

        agua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agua.setText("Agua?");

        luz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        luz.setText("Luz(EPEC)?");

        gas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gas.setText("Gas(ECOGAS)?");

        expensas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expensas.setText("Expensas?");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(legajo58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(luz, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(legajo62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(legajo64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(expensas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 783, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(legajo30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(montoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(legajo31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dgr, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(legajo32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(impuestoMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(legajo63)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(titularDgr, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(legajo39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(titularImpuestoMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(legajo65)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(titularAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(legajo66)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(titularLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(legajo67)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(titularGas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(legajo68)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(titularExpensas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(legajo38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agua, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(legajo34)
                                    .addComponent(legajo35)
                                    .addComponent(legajo36))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaSubscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(legajo33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(legajo30)
                            .addComponent(legajo34)
                            .addComponent(montoAlquiler)
                            .addComponent(fechaSubscripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(legajo35)
                            .addComponent(fechaInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(legajo36)
                            .addComponent(fechaFinalizacion)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(legajo39, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(legajo32)
                                .addComponent(titularImpuestoMunicipal)
                                .addComponent(impuestoMunicipal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(legajo63)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(legajo31)
                                .addComponent(titularDgr)
                                .addComponent(dgr)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(legajo33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(legajo38)
                                .addComponent(legajo65)
                                .addComponent(titularAgua)
                                .addComponent(agua)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titularLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(legajo58)
                                .addComponent(legajo66)
                                .addComponent(luz)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(legajo62)
                            .addComponent(legajo67)
                            .addComponent(titularGas)
                            .addComponent(gas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(legajo64)
                            .addComponent(legajo68)
                            .addComponent(titularExpensas)
                            .addComponent(expensas))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        btnDetallesLocador.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDetallesLocador.setText("Ver detalles del locador");

        btnDetallesInmueble.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDetallesInmueble.setText("Ver detalles del inmueble");

        btnDetallesLocatario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDetallesLocatario.setText("Ver detalles del locatario");

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnImprimir.setText("Imprimir resumen del legajo");

        btnGenerarRecibo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnGenerarRecibo.setText("Generar recibo");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetallesLocatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetallesLocador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetallesInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerarRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnDetallesInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetallesLocador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetallesLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                .addComponent(btnGenerarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel agua;
    public javax.swing.JLabel barrio;
    public javax.swing.JButton btnDetallesInmueble;
    public javax.swing.JButton btnDetallesLocador;
    public javax.swing.JButton btnDetallesLocatario;
    public javax.swing.JButton btnGenerarRecibo;
    public javax.swing.JButton btnImprimir;
    public javax.swing.JLabel dgr;
    public javax.swing.JLabel direccion;
    public javax.swing.JLabel estado;
    public javax.swing.JLabel expensas;
    public javax.swing.JLabel fechaFinalizacion;
    public javax.swing.JLabel fechaInicio;
    public javax.swing.JLabel fechaSubscripcion;
    public javax.swing.JLabel garante1Domicilio;
    public javax.swing.JLabel garante1Mail;
    public javax.swing.JLabel garante1Nombre;
    public javax.swing.JLabel garante1Telefono;
    public javax.swing.JLabel garante2Domicilio;
    public javax.swing.JLabel garante2Mail;
    public javax.swing.JLabel garante2Nombre;
    public javax.swing.JLabel garante2Telefono;
    public javax.swing.JLabel garante3Domicilio;
    public javax.swing.JLabel garante3Mail;
    public javax.swing.JLabel garante3Nombre;
    public javax.swing.JLabel garante3Telefono;
    public javax.swing.JLabel garante4Domicilio;
    public javax.swing.JLabel garante4Mail;
    public javax.swing.JLabel garante4Nombre;
    public javax.swing.JLabel garante4Telefono;
    public javax.swing.JLabel gas;
    public javax.swing.JLabel impuestoMunicipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label8;
    public javax.swing.JLabel legajo;
    private javax.swing.JLabel legajo10;
    private javax.swing.JLabel legajo11;
    private javax.swing.JLabel legajo12;
    private javax.swing.JLabel legajo13;
    private javax.swing.JLabel legajo14;
    private javax.swing.JLabel legajo15;
    private javax.swing.JLabel legajo16;
    private javax.swing.JLabel legajo17;
    private javax.swing.JLabel legajo18;
    private javax.swing.JLabel legajo19;
    private javax.swing.JLabel legajo2;
    private javax.swing.JLabel legajo20;
    private javax.swing.JLabel legajo21;
    private javax.swing.JLabel legajo22;
    private javax.swing.JLabel legajo23;
    private javax.swing.JLabel legajo24;
    private javax.swing.JLabel legajo25;
    private javax.swing.JLabel legajo26;
    private javax.swing.JLabel legajo27;
    private javax.swing.JLabel legajo28;
    private javax.swing.JLabel legajo29;
    private javax.swing.JLabel legajo3;
    private javax.swing.JLabel legajo30;
    private javax.swing.JLabel legajo31;
    private javax.swing.JLabel legajo32;
    private javax.swing.JLabel legajo33;
    private javax.swing.JLabel legajo34;
    private javax.swing.JLabel legajo35;
    private javax.swing.JLabel legajo36;
    private javax.swing.JLabel legajo37;
    private javax.swing.JLabel legajo38;
    private javax.swing.JLabel legajo39;
    private javax.swing.JLabel legajo4;
    private javax.swing.JLabel legajo40;
    private javax.swing.JLabel legajo5;
    private javax.swing.JLabel legajo58;
    private javax.swing.JLabel legajo6;
    private javax.swing.JLabel legajo62;
    private javax.swing.JLabel legajo63;
    private javax.swing.JLabel legajo64;
    private javax.swing.JLabel legajo65;
    private javax.swing.JLabel legajo66;
    private javax.swing.JLabel legajo67;
    private javax.swing.JLabel legajo68;
    private javax.swing.JLabel legajo7;
    private javax.swing.JLabel legajo8;
    private javax.swing.JLabel legajo9;
    public javax.swing.JLabel locadorDomicilio;
    public javax.swing.JLabel locadorMail;
    public javax.swing.JLabel locadorNombre;
    public javax.swing.JLabel locadorTelefono;
    public javax.swing.JLabel locatarioMail;
    public javax.swing.JLabel locatarioNombre;
    public javax.swing.JLabel locatarioTelefono;
    public javax.swing.JLabel luz;
    private javax.swing.JLabel montoAlquiler;
    public javax.swing.JTextArea observaciones;
    public javax.swing.JLabel pisoDepto;
    public javax.swing.JLabel tipoInmueble;
    public javax.swing.JLabel titularAgua;
    public javax.swing.JLabel titularDgr;
    public javax.swing.JLabel titularExpensas;
    public javax.swing.JLabel titularGas;
    public javax.swing.JLabel titularImpuestoMunicipal;
    public javax.swing.JLabel titularLuz;
    public javax.swing.JTextArea txtOtrosGarantes;
    // End of variables declaration//GEN-END:variables
}
